version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: preds
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file: .env
    depends_on:
      - api
    ports:
      - "8501:8501"

  monitoring:
    build:
      context: .
      dockerfile: monitoring/Dockerfile
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8502:8502"

volumes:
  pgdata:
