FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy Streamlit app
COPY monitoring/ ./monitoring/

# Streamlit + API settings
ENV API_URL=http://api:8000
ENV STREAMLIT_SERVER_HEADLESS=true

EXPOSE 8501

CMD ["streamlit", "run", "monitoring/app.py", "--server.port=8501", "--server.address=0.0.0.0"]